#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Aug 03, 2024 12:38:57 AM +0300  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    folder_png "F:\\University\\Project\\Pathomic 4\\Assets\\folder.png"
    mongodb_png "F:\\University\\Project\\Pathomic 4\\Assets\\mongodb.png"
    smalllogo_jpg "F:\\University\\Project\\Pathomic 4\\Assets\\smalllogo.jpg"
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 785x615+264+139
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1031
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -image smalllogo_jpg -padx 0 -pady 0 
    vTcl:DefineAlias "$top.lab47" "imgLogo" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab48" \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -text "Dataset Inputs" -background #d9d9d9 -height 350 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 256 
    vTcl:DefineAlias "$top.lab48" "frmInputs" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab48
    label "$site_3_0.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Input Dataset:" 
    vTcl:DefineAlias "$site_3_0.lab49" "lblInputDatasetLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab79" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Input File Type:" 
    vTcl:DefineAlias "$site_3_0.lab79" "lblInputFileTypeLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab81" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Output File Type:" 
    vTcl:DefineAlias "$site_3_0.lab81" "lblOutputFileTypeLabel" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$site_3_0.lab77" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Image Properties" -background #d9d9d9 -height 125 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 240 
    vTcl:DefineAlias "$site_3_0.lab77" "frmImageProperties" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab77
    label "$site_4_0.lab78" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Width:" 
    vTcl:DefineAlias "$site_4_0.lab78" "lblWidthLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab80" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Height:" 
    vTcl:DefineAlias "$site_4_0.lab80" "lblHeightLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_4_0.lab82" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Channels:" 
    vTcl:DefineAlias "$site_4_0.lab82" "lblChannelsLabel" vTcl:WidgetProc "Toplevel1" 1
    text "$site_4_0.tex49" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 124 \
        -wrap word 
    $site_4_0.tex49 configure -font "TkTextFont"
    $site_4_0.tex49 insert end text
    vTcl:DefineAlias "$site_4_0.tex49" "txtWidth" vTcl:WidgetProc "Toplevel1" 1
    text "$site_4_0.tex81" \
        -background white -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -insertbackground #000000 \
        -selectbackground #d9d9d9 -selectforeground black -width 124 \
        -wrap word 
    $site_4_0.tex81 configure -font "TkTextFont"
    $site_4_0.tex81 insert end text
    vTcl:DefineAlias "$site_4_0.tex81" "txtHeight" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_4_0.tCo83" \
        -font "-family {Segoe UI} -size 9" -textvariable "patch_channels" 
    vTcl:DefineAlias "$site_4_0.tCo83" "cmbChannels" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab78 \
        -in $site_4_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab80 \
        -in $site_4_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.lab82 \
        -in $site_4_0 -x 10 -y 90 -anchor nw -bordermode ignore 
    place $site_4_0.tex49 \
        -in $site_4_0 -x 100 -y 30 -width 124 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex81 \
        -in $site_4_0 -x 100 -y 60 -width 124 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tCo83 \
        -in $site_4_0 -x 100 -y 90 -width 127 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    label "$site_3_0.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Local Path" 
    vTcl:DefineAlias "$site_3_0.lab54" "lblLocalPathLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "MongoDB" 
    vTcl:DefineAlias "$site_3_0.lab58" "lblMongoDBLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Cloud" 
    vTcl:DefineAlias "$site_3_0.lab51" "lblCloudLabel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but58" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$site_3_0.but58" "btnLocal" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but59" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$site_3_0.but59" "btnMongo" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but60" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    vTcl:DefineAlias "$site_3_0.but60" "btnCloud" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "<Dataset Path>" -textvariable "dataset_path" 
    vTcl:DefineAlias "$site_3_0.lab50" "lblInputDataset" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo80" \
        -font "-family {Segoe UI} -size 9" -textvariable "input_file_type" 
    vTcl:DefineAlias "$site_3_0.tCo80" "cmbInputTypes" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox "$site_3_0.tCo82" \
        -font "-family {Segoe UI} -size 9" -textvariable "output_file_type" 
    vTcl:DefineAlias "$site_3_0.tCo82" "cmbOutputTypes" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab49 \
        -in $site_3_0 -x 10 -y 20 -width 92 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab79 \
        -in $site_3_0 -x 10 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 10 -y 200 -anchor nw -bordermode ignore 
    place $site_3_0.lab77 \
        -in $site_3_0 -x 10 -y 220 -width 236 -relwidth 0 -height 125 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 8 -y 140 -width 67 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 88 -y 140 -width 64 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 173 -y 140 -width 53 -relwidth 0 -height 27 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 8 -y 88 -width 48 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but59 \
        -in $site_3_0 -x 88 -y 88 -width 48 -relwidth 0 -height 48 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but60 \
        -in $site_3_0 -x 180 -y 80 -width 50 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 10 -y 50 -width 230 -relwidth 0 -height 14 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo80 \
        -in $site_3_0 -x 130 -y 170 -width 107 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo82 \
        -in $site_3_0 -x 130 -y 200 -width 107 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab68" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Image Labeling & QuPath" -background #d9d9d9 -height 270 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 246 
    vTcl:DefineAlias "$top.lab68" "frmQuPath" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab68
    label "$site_3_0.lab75" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Status:" 
    vTcl:DefineAlias "$site_3_0.lab75" "lblQuPathStatusLabel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but77" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "QuPath Parameters" 
    vTcl:DefineAlias "$site_3_0.but77" "btnQuPathParams" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but71" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "QuPath Analysis" 
    vTcl:DefineAlias "$site_3_0.but71" "btnQuPathAnalysis" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab76" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Ready for labeling." -textvariable "qupath_status" 
    vTcl:DefineAlias "$site_3_0.lab76" "lblQuPathStatus" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar "$site_3_0.tPr78" \
        -length 230 -variable "qupath_progress" 
    vTcl:DefineAlias "$site_3_0.tPr78" "pbQuPath" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab75 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.but77 \
        -in $site_3_0 -x 10 -y 70 -width 227 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 10 -y 100 -width 227 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 60 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.tPr78 \
        -in $site_3_0 -x 10 -y 40 -width 230 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab61" \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -text "Normalization" -background #d9d9d9 -height 165 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 246 
    vTcl:DefineAlias "$top.lab61" "frmNormalization" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab61
    label "$site_3_0.lab73" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Status:" 
    vTcl:DefineAlias "$site_3_0.lab73" "lblNormStatusLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab69" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Normalization Algorithm:" 
    vTcl:DefineAlias "$site_3_0.lab69" "lblNormAlgoLabel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but65" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Load Model" 
    vTcl:DefineAlias "$site_3_0.but65" "btnNormLoadModel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but56" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Train Model" 
    vTcl:DefineAlias "$site_3_0.but56" "btnNormTrainModel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but62" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Normalize" 
    vTcl:DefineAlias "$site_3_0.but62" "btnNormalize" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab70" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Histogram" -textvariable "norm_algo_name" 
    vTcl:DefineAlias "$site_3_0.lab70" "lblNormAlgo" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab74" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Ready for Normalization." -textvariable "norm_status" 
    vTcl:DefineAlias "$site_3_0.lab74" "lblNormStatus" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar "$site_3_0.tPr72" \
        -length 230 -variable "norm_progress" 
    vTcl:DefineAlias "$site_3_0.tPr72" "pbNorm" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab73 \
        -in $site_3_0 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab69 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 10 -y 100 -width 117 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 130 -y 100 -width 107 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but62 \
        -in $site_3_0 -x 10 -y 130 -width 227 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab70 \
        -in $site_3_0 -x 160 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 60 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.tPr72 \
        -in $site_3_0 -x 10 -y 70 -width 230 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab66" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Preprocess & ROI" -background #d9d9d9 -height 165 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 246 
    vTcl:DefineAlias "$top.lab66" "frmROI" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab66
    label "$site_3_0.lab71" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Status:" 
    vTcl:DefineAlias "$site_3_0.lab71" "lblROIStatusLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab65" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Filter Algorithm:" 
    vTcl:DefineAlias "$site_3_0.lab65" "lblROIAlgorithmLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab72" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Ready for filtering." -textvariable "roi_status" 
    vTcl:DefineAlias "$site_3_0.lab72" "lblROIStatus" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Hard coded filter." -textvariable "roi_algo_name" 
    vTcl:DefineAlias "$site_3_0.lab67" "lblROIAlgorithm" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but67" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Filter Dataset" 
    vTcl:DefineAlias "$site_3_0.but67" "btnROIFilter" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but47" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Load Model" 
    vTcl:DefineAlias "$site_3_0.but47" "btnROILoadModel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but57" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Train Model" 
    vTcl:DefineAlias "$site_3_0.but57" "btnROITrainModel" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar "$site_3_0.tPr47" \
        -length 230 -variable "roi_progress" 
    vTcl:DefineAlias "$site_3_0.tPr47" "pbROI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab71 \
        -in $site_3_0 -x 10 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 60 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab67 \
        -in $site_3_0 -x 110 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 10 -y 130 -width 227 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 10 -y 100 -width 117 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 130 -y 100 -width 107 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr47 \
        -in $site_3_0 -x 10 -y 70 -width 230 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab55" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -text "Results" -background #d9d9d9 -height 440 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -width 256 
    vTcl:DefineAlias "$top.lab55" "frmResultsframe" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab55
    label "$site_3_0.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Processed Dataset:" 
    vTcl:DefineAlias "$site_3_0.lab60" "lblProcessedDatasetLabel" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Results Outputs:" 
    vTcl:DefineAlias "$site_3_0.lab63" "lblResultsDatasetLabel" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but54" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Intensity Distribution" 
    vTcl:DefineAlias "$site_3_0.but54" "btnIntensity" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "PCA Results" 
    vTcl:DefineAlias "$site_3_0.but50" "btnPCA" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but61" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "K-Means Results" 
    vTcl:DefineAlias "$site_3_0.but61" "btnKMeans" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Confusion Matrix" 
    vTcl:DefineAlias "$site_3_0.but51" "btnCOX" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but52" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Feature Distribution Groups" 
    vTcl:DefineAlias "$site_3_0.but52" "btnFeatures" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but49" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Anova Table" 
    vTcl:DefineAlias "$site_3_0.but49" "btnAnova" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but53" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Kaplan-Meir Graph" 
    vTcl:DefineAlias "$site_3_0.but53" "btnKaplanMeier" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but63" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "QTL Results" 
    vTcl:DefineAlias "$site_3_0.but63" "btnQTLResults" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but55" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Generate Report" 
    vTcl:DefineAlias "$site_3_0.but55" "btnGenerate" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab62" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "<Dataset Output>" -textvariable "processed_path" 
    vTcl:DefineAlias "$site_3_0.lab62" "lblProcessedDataset" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab64" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "<Output Path>" -textvariable "results_path" 
    vTcl:DefineAlias "$site_3_0.lab64" "lblResultsDataset" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 10 -y 110 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 10 -y 140 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 10 -y 170 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 10 -y 200 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 10 -y 230 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 10 -y 260 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 10 -y 290 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but63 \
        -in $site_3_0 -x 10 -y 320 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but55 \
        -in $site_3_0 -x 10 -y 350 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 10 -y 40 -width 232 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 80 -width 237 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe "$top.lab53" \
        -font "-family {Segoe UI} -size 9" -foreground #000000 -text "Train" \
        -background #d9d9d9 -height 166 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 256 
    vTcl:DefineAlias "$top.lab53" "frmTrain" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab53
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Model Status:" 
    vTcl:DefineAlias "$site_3_0.lab56" "lblModelStatusLabel" vTcl:WidgetProc "Toplevel1" 1
    ttk::progressbar "$site_3_0.tPr60" \
        -length 220 
    vTcl:DefineAlias "$site_3_0.tPr60" "pbTrain" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but48" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Train Pathomics Models" 
    vTcl:DefineAlias "$site_3_0.but48" "btnTrainPathomics" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9 -weight bold" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -text "Options:" 
    vTcl:DefineAlias "$site_3_0.lab52" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab59" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -text "Model not loaded." -textvariable "pathomics_status" 
    vTcl:DefineAlias "$site_3_0.lab59" "lblModelStatus" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$site_3_0.che51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "Kaplan-Meir" -variable "kaplan_meier" 
    vTcl:DefineAlias "$site_3_0.che51" "cbKaplanMeier" vTcl:WidgetProc "Toplevel1" 1
    checkbutton "$site_3_0.che47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background #d9d9d9 -compound left -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 9" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 -justify left \
        -text "QTL" -variable "qtl" 
    vTcl:DefineAlias "$site_3_0.che47" "cbQTL" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 10 -y 20 -width 102 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tPr60 \
        -in $site_3_0 -x 10 -y 40 -width 236 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 10 -y 70 -width 237 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 10 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 90 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che51 \
        -in $site_3_0 -x 70 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.che47 \
        -in $site_3_0 -x 70 -y 120 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab47 \
        -in $top -x 5 -y 5 -width 256 -relwidth 0 -height 256 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 10 -y 260 -width 256 -relwidth 0 -height 350 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab68 \
        -in $top -x 270 -y 340 -width 246 -relwidth 0 -height 270 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 270 -y 170 -width 246 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 270 -y 0 -width 246 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 520 -y 170 -width 256 -relwidth 0 -height 440 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 520 -y 0 -width 256 -relwidth 0 -height 166 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

